version: '3.7'

services:
  siftwebhook:
    container_name: siftwebhook
    image: siftwebhook/siftwebhook:latest
    build:
      context: ../
      dockerfile:  ./docker/Dockerfile
    ports:
      - "1337:1337"
    restart: always
    networks:
      - insure2go-network
networks:
  insure2go-network:
    driver: bridge
