version: '3.7'

services:
  siftchatbot:
    container_name: siftchatbot
    image: siftchatbot/siftchatbot:latest
    build:
      context: ../
      dockerfile:  ./docker/Dockerfile
    ports:
      - "1337:1337"
    restart: always
    networks:
      - insure2go-network
networks:
  insure2go-network:
    driver: bridge
